In [2]:
pip install numpy

   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   -- ------------------------------------- 0.8/12.6 MB 11.7 MB/s eta 0:00:02
   ---------- ----------------------------- 3.4/12.6 MB 11.7 MB/s eta 0:00:01
   ------------------ --------------------- 5.8/12.6 MB 11.7 MB/s eta 0:00:01
   ------------------------- -------------- 8.1/12.6 MB 11.6 MB/s eta 0:00:01
   -------------------------------- ------- 10.2/12.6 MB 11.2 MB/s eta 0:00:01
   -------------------------------------- - 12.1/12.6 MB 10.5 MB/s eta 0:00:01
   ---------------------------------------- 12.6/12.6 MB 9.8 MB/s  0:00:01
Note: you may need to restart the kernel to use updated packages.


  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

[notice] A new release of pip is available: 26.0.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [4]:
# import library
import numpy as np

In [5]:
# create an array
x = np.array([1,2,3])
x

array([1, 2, 3])

In [6]:
# check the type
type(x)

numpy.ndarray

In [7]:
np.arange(1,101)

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [10]:
# basic operations 
x1 = np.arange(0,10)
x2 = np.arange(0,10)
print(x1 + x2)

[ 0  2  4  6  8 10 12 14 16 18]


In [11]:
x1 * x2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [13]:
rev_q1 = np.array([10,12,9])

In [14]:
rev_q1

array([10, 12,  9])

In [16]:
rev_q1.ndim # check number of dimension

1

So, rev_q1 is one dimensional array. 

In [17]:
# create a multi-dimensional array
rev = np.array([[10,12,9], [15,11,9]])

In [18]:
rev

array([[10, 12,  9],
       [15, 11,  9]])

In [19]:
rev.ndim

2

In [23]:
# 1st element of the 2nd array (row)
print(rev[1][0])

15


In [24]:
# or, 
print(rev[1,0])

15


In [25]:
rev[1,0] = 14

In [26]:
rev

array([[10, 12,  9],
       [14, 11,  9]])

In [28]:
# check data type
rev.dtype

dtype('int64')

In [29]:
rev.shape

(2, 3)

So, it has 2 rows and 3 columns.

In [33]:
x = np.array([[10,12,9],[15,11,13]])
np.sort(x, axis=None) # sorts all elements of the array as if it were flattened into a 1D array

array([ 9, 10, 11, 12, 13, 15])

np.sort(array, axis=-1) sorts the array along the last axis.
For a 2D array, axis=-1 is equivalent to axis=1, meaning each row is sorted independently.

In [34]:
np.sort(x, axis=-1)

array([[ 9, 10, 12],
       [11, 13, 15]])

In [37]:
np.zeros((2,3)) # Return a new array of given shape and type, filled with zeros.

array([[0., 0., 0.],
       [0., 0., 0.]])

In [38]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [39]:
np.ones((2,3)).dtype

dtype('float64')

In [40]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [41]:
np.arange(10,20,2)

array([10, 12, 14, 16, 18])

In [42]:
np.linspace(2.0, 3.0, num=5) # creates an array of evenly spaced numbers between a start and an end value. 

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

In [48]:
x

array([[10, 12,  9],
       [15, 11, 13]])

In [49]:
x.flatten()

array([10, 12,  9, 15, 11, 13])

In [50]:
x

array([[10, 12,  9],
       [15, 11, 13]])

In [51]:
x.shape

(2, 3)

In [52]:
x.reshape(-1)

array([10, 12,  9, 15, 11, 13])

In [56]:
x.min()

np.int64(9)

In [57]:
x.max()

np.int64(15)

In [58]:
x.sum()

np.int64(70)

In [59]:
x.sum(axis=-1)

array([31, 39])

In [64]:
x

array([[10, 12,  9],
       [15, 11, 13]])

In [65]:
x.max(axis=0) # returns the maximum value from each column.

array([15, 12, 13])

In [66]:
x.max(axis=1) # returns the maximum value from each row.

array([12, 15])

In [68]:
y = np.array([1,4,16])

In [69]:
np.sqrt(y)

array([1., 2., 4.])